//
//  EventData.swift
//  SeventhBuildingApp0119
//
//  Created by cmStudent on 2021/08/19.
//

import Foundation
import UIKit

struct EventData {
    let floor: String
    let field: String
    let subject: String
    let startTime: String
    let detail: String
    let floorImage: String
    let shadow: UIColor
}

class Event {
    
    static var eventList: [EventData] = [
        EventData(floor: "9F 792教室",
                  field: Subject.subjectList[4].field,
                  subject: Subject.subjectList[4].subject[1],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容",
                  floorImage: "792",shadow: .electricFieldColor),
        EventData(floor: "9F 792教室",
                  field: Subject.subjectList[4].field,
                  subject: Subject.subjectList[4].subject[1],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容",
                  floorImage: "792",shadow: .electricFieldColor),
        EventData(floor: "9F 792教室",
                  field: Subject.subjectList[4].field,
                  subject: Subject.subjectList[4].subject[1],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容",
                  floorImage: "792",shadow: .electricFieldColor),
        EventData(floor: "6F 762教室",
                  field: Subject.subjectList[7].field,
                  subject: Subject.subjectList[7].subject[0],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容",
                  floorImage: "762",shadow: .dataProcessingFieldColor),
        EventData(floor: "6F 762教室",
                  field: Subject.subjectList[7].field,
                  subject: Subject.subjectList[7].subject[0],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容",
                  floorImage: "762",shadow: .dataProcessingFieldColor),
        EventData(floor: "6F 762教室",
                  field: Subject.subjectList[7].field,
                  subject: Subject.subjectList[7].subject[0],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容",
                  floorImage: "762",shadow: .dataProcessingFieldColor),
        EventData(floor: "3F 732教室",
                  field: Subject.subjectList[5].field,
                  subject: Subject.subjectList[5].subject[0],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容",
                  floorImage: "732",shadow: .gameFieldColor),
        EventData(floor: "3F 732教室",
                  field: Subject.subjectList[5].field,
                  subject: Subject.subjectList[5].subject[0],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容",
                  floorImage: "732",shadow: .gameFieldColor),
        EventData(floor: "3F 732教室",
                  field: Subject.subjectList[5].field,
                  subject: Subject.subjectList[5].subject[0],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容",
                  floorImage: "732",shadow: .gameFieldColor),
        EventData(floor: "8F 781教室",
                  field: Subject.subjectList[9].field,
                  subject: Subject.subjectList[9].subject[1],
                  startTime: "09 / 21 AM : 10 : 00 ~ 12 : 00",
                  detail: "イベント内容イベント内容",
                  floorImage: "781",shadow: .webFieldColor),
        EventData(floor: "8F 781教室",
                  field: Subject.subjectList[9].field,
                  subject: Subject.subjectList[9].subject[1],
                  startTime: "09 / 21 AM : 10 : 00 ~ 12 : 00",
                  detail: "イベント内容イベント内容",
                  floorImage: "781",shadow: .webFieldColor),
        EventData(floor: "8F 781教室",
                  field: Subject.subjectList[9].field,
                  subject: Subject.subjectList[9].subject[1],
                  startTime: "09 / 21 AM : 10 : 00 ~ 12 : 00",
                  detail: "イベント内容イベント内容",
                  floorImage: "781",shadow: .webFieldColor),
        EventData(floor: "8F 782教室",
                  field: Subject.subjectList[9].field,
                  subject: Subject.subjectList[9].subject[1],
                  startTime: "09 / 21 AM : 10 : 00 ~ 12 : 00",
                  detail: "イベント内容イベント内容",
                  floorImage: "782",shadow: .webFieldColor),
        EventData(floor: "9F 791教室",
                  field: Subject.subjectList[4].field,
                  subject: Subject.subjectList[4].subject[0],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容",
                  floorImage: "791",shadow: .electricFieldColor),
        EventData(floor: "9F 791教室",
                  field: Subject.subjectList[4].field,
                  subject: Subject.subjectList[4].subject[0],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容",
                  floorImage: "791",shadow: .electricFieldColor),
        EventData(floor: "9F 791教室",
                  field: Subject.subjectList[4].field,
                  subject: Subject.subjectList[4].subject[0],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容",
                  floorImage: "791",shadow: .electricFieldColor),
        EventData(floor: "3F 731教室",
                  field: Subject.subjectList[5].field,
                  subject: Subject.subjectList[5].subject[1],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容",
                  floorImage: "731",shadow: .gameFieldColor),
        EventData(floor: "3F 731教室",
                  field: Subject.subjectList[5].field,
                  subject: Subject.subjectList[5].subject[1],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容",
                  floorImage: "731",shadow: .gameFieldColor),
        EventData(floor: "3F 731教室",
                  field: Subject.subjectList[5].field,
                  subject: Subject.subjectList[5].subject[1],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容",
                  floorImage: "731",shadow: .gameFieldColor),
        EventData(floor: "6F 761教室",
                  field: Subject.subjectList[7].field,
                  subject: Subject.subjectList[7].subject[1],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容",
                  floorImage: "761",shadow: .dataProcessingFieldColor),
        EventData(floor: "6F 761教室",
                  field: Subject.subjectList[7].field,
                  subject: Subject.subjectList[7].subject[1],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容",
                  floorImage: "761",shadow: .dataProcessingFieldColor),
        EventData(floor: "6F 761教室",
                  field: Subject.subjectList[7].field,
                  subject: Subject.subjectList[7].subject[1],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容",
                  floorImage: "761",shadow: .dataProcessingFieldColor),
        EventData(floor: "B1F 7B11教室",
                  field: Subject.subjectList[3].field,
                  subject: Subject.subjectList[3].subject[0],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容",
                  floorImage: "7B11",shadow: .businessFieldColor),
        EventData(floor: "B1F 7B11教室",
                  field: Subject.subjectList[3].field,
                  subject: Subject.subjectList[3].subject[0],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容",
                  floorImage: "7B11",shadow: .businessFieldColor),
        EventData(floor: "B1F 7B11教室",
                  field: Subject.subjectList[3].field,
                  subject: Subject.subjectList[3].subject[0],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容",
                  floorImage: "7B11",shadow: .businessFieldColor),
        EventData(floor: "B1F 7B12教室",
                  field: Subject.subjectList[10].field,
                  subject: Subject.subjectList[10].subject[0],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容",
                  floorImage: "7B12",shadow: .networkFieldColor),
        EventData(floor: "B1F 7B12教室",
                  field: Subject.subjectList[10].field,
                  subject: Subject.subjectList[10].subject[0],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容",
                  floorImage: "7B12",shadow: .networkFieldColor),
        EventData(floor: "B1F 7B12教室",
                  field: Subject.subjectList[10].field,
                  subject: Subject.subjectList[10].subject[0],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容",
                  floorImage: "7B12",shadow: .networkFieldColor),
        EventData(floor: "4F 742教室",
                  field: Subject.subjectList[1].field,
                  subject: Subject.subjectList[1].subject[0],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容",
                  floorImage: "742",shadow: .cgFieldColor),
        EventData(floor: "4F 742教室",
                  field: Subject.subjectList[1].field,
                  subject: Subject.subjectList[1].subject[0],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容",
                  floorImage: "742",shadow: .cgFieldColor),
        EventData(floor: "4F 742教室",
                  field: Subject.subjectList[1].field,
                  subject: Subject.subjectList[1].subject[0],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容",
                  floorImage: "742",shadow: .cgFieldColor),
        EventData(floor: "B2F 7B22教室",
                  field: Subject.subjectList[6].field,
                  subject: Subject.subjectList[6].subject[0],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容",
                  floorImage: "7B22",shadow: .aiFieldColor),
        EventData(floor: "B2F 7B22教室",
                  field: Subject.subjectList[6].field,
                  subject: Subject.subjectList[6].subject[0],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容",
                  floorImage: "7B22",shadow: .aiFieldColor),
        EventData(floor: "B2F 7B22教室",
                  field: Subject.subjectList[6].field,
                  subject: Subject.subjectList[6].subject[0],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容",
                  floorImage: "7B22",shadow: .aiFieldColor),
        EventData(floor: "7F 772教室",
                  field: Subject.subjectList[9].field,
                  subject: Subject.subjectList[9].subject[0],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容",
                  floorImage: "772",shadow: .webFieldColor),
        EventData(floor: "7F 772教室",
                  field: Subject.subjectList[9].field,
                  subject: Subject.subjectList[9].subject[0],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容",
                  floorImage: "772",shadow: .webFieldColor),
        EventData(floor: "7F 772教室",
                  field: Subject.subjectList[9].field,
                  subject: Subject.subjectList[9].subject[0],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容",
                  floorImage: "772",shadow: .webFieldColor),
        EventData(floor: "7F 771教室",
                  field: Subject.subjectList[9].field,
                  subject: Subject.subjectList[9].subject[0],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容",
                  floorImage: "771",shadow: .webFieldColor),
        EventData(floor: "7F 771教室",
                  field: Subject.subjectList[9].field,
                  subject: Subject.subjectList[9].subject[0],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容",
                  floorImage: "771",shadow: .webFieldColor),
        EventData(floor: "7F 771教室",
                  field: Subject.subjectList[9].field,
                  subject: Subject.subjectList[9].subject[0],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容",
                  floorImage: "771",shadow: .webFieldColor),
        EventData(floor: "7F 773教室",
                  field: Subject.subjectList[9].field,
                  subject: Subject.subjectList[9].subject[0],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容",
                  floorImage: "773",shadow: .webFieldColor),
        EventData(floor: "7F 773教室",
                  field: Subject.subjectList[9].field,
                  subject: Subject.subjectList[9].subject[0],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容",
                  floorImage: "773",shadow: .webFieldColor),
        EventData(floor: "7F 773教室",
                  field: Subject.subjectList[9].field,
                  subject: Subject.subjectList[9].subject[0],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容",
                  floorImage: "773",shadow: .webFieldColor),
        EventData(floor: "4F 743教室",
                  field: Subject.subjectList[1].field,
                  subject: Subject.subjectList[1].subject[1],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容",
                  floorImage: "743",shadow: .cgFieldColor),
        EventData(floor: "4F 743教室",
                  field: Subject.subjectList[1].field,
                  subject: Subject.subjectList[1].subject[1],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容",
                  floorImage: "743",shadow: .cgFieldColor),
        EventData(floor: "4F 743教室",
                  field: Subject.subjectList[1].field,
                  subject: Subject.subjectList[1].subject[1],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容",
                  floorImage: "743",shadow: .cgFieldColor),
        EventData(floor: "5F 751教室",
                  field: Subject.subjectList[8].field,
                  subject: Subject.subjectList[8].subject[1],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容",
                  floorImage: "751",shadow: .animationFieldColor),
        EventData(floor: "5F 751教室",
                  field: Subject.subjectList[8].field,
                  subject: Subject.subjectList[8].subject[1],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容",
                  floorImage: "751",shadow: .animationFieldColor),
        EventData(floor: "5F 751教室",
                  field: Subject.subjectList[8].field,
                  subject: Subject.subjectList[8].subject[1],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容",
                  floorImage: "751",shadow: .animationFieldColor),
        EventData(floor: "5F 753教室",
                  field: Subject.subjectList[8].field,
                  subject: Subject.subjectList[8].subject[1],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容",
                  floorImage: "753",shadow: .animationFieldColor),
        EventData(floor: "5F 753教室",
                  field: Subject.subjectList[8].field,
                  subject: Subject.subjectList[8].subject[1],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容",
                  floorImage: "753",shadow: .animationFieldColor),
        EventData(floor: "5F 753教室",
                  field: Subject.subjectList[8].field,
                  subject: Subject.subjectList[8].subject[1],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容",
                  floorImage: "753",shadow: .animationFieldColor),
        EventData(floor: "9F 792教室",
                  field: Subject.subjectList[4].field,
                  subject: Subject.subjectList[4].subject[3],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容",
                  floorImage: "792",shadow: .electricFieldColor),
        EventData(floor: "9F 792教室",
                  field: Subject.subjectList[4].field,
                  subject: Subject.subjectList[4].subject[3],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容",
                  floorImage: "792",shadow: .electricFieldColor),
        EventData(floor: "9F 792教室",
                  field: Subject.subjectList[4].field,
                  subject: Subject.subjectList[4].subject[3],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容",
                  floorImage: "792",shadow: .electricFieldColor),
        EventData(floor: "6F 763教室",
                  field: Subject.subjectList[7].field,
                  subject: Subject.subjectList[7].subject[2],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容",
                  floorImage: "763",shadow: .dataProcessingFieldColor),
        EventData(floor: "6F 763教室",
                  field: Subject.subjectList[7].field,
                  subject: Subject.subjectList[7].subject[2],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容っ",
                  floorImage: "763",shadow: .dataProcessingFieldColor),
        EventData(floor: "6F 763教室",
                  field: Subject.subjectList[7].field,
                  subject: Subject.subjectList[7].subject[2],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容っっっj",
                  floorImage: "763",shadow: .dataProcessingFieldColor),
        EventData(floor: "B1F 7B14教室",
                  field: Subject.subjectList[2].field,
                  subject: Subject.subjectList[2].subject[0],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容っっっっっっっっっっっっっっっっ",
                  floorImage: "7B14",shadow: .designFieldColor),
        EventData(floor: "B1F 7B14教室",
                  field: Subject.subjectList[2].field,
                  subject: Subject.subjectList[2].subject[0],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容っっっっっっっっっっっっっっっ",
                  floorImage: "7B14",shadow: .designFieldColor),
        EventData(floor: "B1F 7B14教室",
                  field: Subject.subjectList[2].field,
                  subject: Subject.subjectList[2].subject[0],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容っっっっっっっっっっっっ",
                  floorImage: "7B14",shadow: .designFieldColor),
        EventData(floor: "4 741教室",
                  field: Subject.subjectList[1].field,
                  subject: Subject.subjectList[1].subject[2],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容っっっっっっっっっっっっ",
                  floorImage: "741",shadow: .cgFieldColor),
        EventData(floor: "4F 741教室",
                  field: Subject.subjectList[1].field,
                  subject: Subject.subjectList[1].subject[2],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容っっっっっっっっっっっっっ",
                  floorImage: "741",shadow: .cgFieldColor),
        EventData(floor: "4F 741教室",
                  field: Subject.subjectList[1].field,
                  subject: Subject.subjectList[1].subject[2],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容っっっっっっっっっっっっっっっ",
                  floorImage: "741",shadow: .cgFieldColor),
        EventData(floor: "3F 733教室",
                  field: Subject.subjectList[5].field,
                  subject: Subject.subjectList[5].subject[2],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容",
                  floorImage: "733",shadow: .gameFieldColor),
        EventData(floor: "3F 733教室",
                  field: Subject.subjectList[5].field,
                  subject: Subject.subjectList[5].subject[2],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容っっっっっっっっっっ",
                  floorImage: "733",shadow: .gameFieldColor),
        EventData(floor: "3F 733教室",
                  field: Subject.subjectList[5].field,
                  subject: Subject.subjectList[5].subject[2],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容っっっ",
                  floorImage: "733",shadow: .gameFieldColor),
        EventData(floor: "9F 791教室",
                  field: Subject.subjectList[4].field,
                  subject: Subject.subjectList[4].subject[2],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容",
                  floorImage: "791",shadow: .electricFieldColor),
        EventData(floor: "9F 791教室",
                  field: Subject.subjectList[4].field,
                  subject: Subject.subjectList[4].subject[2],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容",
                  floorImage: "791",shadow: .electricFieldColor),
        EventData(floor: "9F 791教室",
                  field: Subject.subjectList[4].field,
                  subject: Subject.subjectList[4].subject[2],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容っ",
                  floorImage: "791",shadow: .electricFieldColor),
        EventData(floor: "5F 752教室",
                  field: Subject.subjectList[8].field,
                  subject: Subject.subjectList[8].subject[0],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容っ",
                  floorImage: "752",shadow: .animationFieldColor),
        EventData(floor: "5F 752教室",
                  field: Subject.subjectList[8].field,
                  subject: Subject.subjectList[8].subject[0],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容っっっっっっっっっっっっっっっっ",
                  floorImage: "752",shadow: .animationFieldColor),
        EventData(floor: "5F 752教室",
                  field: Subject.subjectList[8].field,
                  subject: Subject.subjectList[8].subject[0],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容っっっっっっっっっっっっっ",
                  floorImage: "752",shadow: .animationFieldColor),
        EventData(floor: "B2F 7B21教室",
                  field: Subject.subjectList[6].field,
                  subject: Subject.subjectList[6].subject[0],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容っっっっっっっっっっっっ",
                  floorImage: "7B21",shadow: .aiFieldColor),
        EventData(floor: "B2F 7B21教室",
                  field: Subject.subjectList[6].field,
                  subject: Subject.subjectList[6].subject[0],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容っっっっっっっっっっっ",
                  floorImage: "7B21",shadow: .aiFieldColor),
        EventData(floor: "B2F 7B21教室",
                  field: Subject.subjectList[6].field,
                  subject: Subject.subjectList[6].subject[0],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容",
                  floorImage: "7B21",shadow: .aiFieldColor),
        
    ]
    
    static var cloneList: [EventData] = [
        EventData(floor: "9F 792教室",
                  field: Subject.subjectList[4].field,
                  subject: Subject.subjectList[4].subject[1],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容",
                  floorImage: "792",shadow: .electricFieldColor),
        EventData(floor: "9F 792教室",
                  field: Subject.subjectList[4].field,
                  subject: Subject.subjectList[4].subject[1],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容",
                  floorImage: "792",shadow: .electricFieldColor),
        EventData(floor: "9F 792教室",
                  field: Subject.subjectList[4].field,
                  subject: Subject.subjectList[4].subject[1],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容",
                  floorImage: "792",shadow: .electricFieldColor),
        EventData(floor: "6F 762教室",
                  field: Subject.subjectList[7].field,
                  subject: Subject.subjectList[7].subject[0],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容",
                  floorImage: "762",shadow: .dataProcessingFieldColor),
        EventData(floor: "6F 762教室",
                  field: Subject.subjectList[7].field,
                  subject: Subject.subjectList[7].subject[0],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容",
                  floorImage: "762",shadow: .dataProcessingFieldColor),
        EventData(floor: "6F 762教室",
                  field: Subject.subjectList[7].field,
                  subject: Subject.subjectList[7].subject[0],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容",
                  floorImage: "762",shadow: .dataProcessingFieldColor),
        EventData(floor: "3F 732教室",
                  field: Subject.subjectList[5].field,
                  subject: Subject.subjectList[5].subject[0],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容",
                  floorImage: "732",shadow: .gameFieldColor),
        EventData(floor: "3F 732教室",
                  field: Subject.subjectList[5].field,
                  subject: Subject.subjectList[5].subject[0],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容",
                  floorImage: "732",shadow: .gameFieldColor),
        EventData(floor: "3F 732教室",
                  field: Subject.subjectList[5].field,
                  subject: Subject.subjectList[5].subject[0],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容",
                  floorImage: "732",shadow: .gameFieldColor),
        EventData(floor: "8F 781教室",
                  field: Subject.subjectList[9].field,
                  subject: Subject.subjectList[9].subject[1],
                  startTime: "09 / 21 AM : 10 : 00 ~ 12 : 00",
                  detail: "イベント内容イベント内容",
                  floorImage: "781",shadow: .webFieldColor),
        EventData(floor: "8F 781教室",
                  field: Subject.subjectList[9].field,
                  subject: Subject.subjectList[9].subject[1],
                  startTime: "09 / 21 AM : 10 : 00 ~ 12 : 00",
                  detail: "イベント内容イベント内容",
                  floorImage: "781",shadow: .webFieldColor),
        EventData(floor: "8F 781教室",
                  field: Subject.subjectList[9].field,
                  subject: Subject.subjectList[9].subject[1],
                  startTime: "09 / 21 AM : 10 : 00 ~ 12 : 00",
                  detail: "イベント内容イベント内容",
                  floorImage: "781",shadow: .webFieldColor),
        EventData(floor: "8F 782教室",
                  field: Subject.subjectList[9].field,
                  subject: Subject.subjectList[9].subject[1],
                  startTime: "09 / 21 AM : 10 : 00 ~ 12 : 00",
                  detail: "イベント内容イベント内容",
                  floorImage: "782",shadow: .webFieldColor),
        EventData(floor: "9F 791教室",
                  field: Subject.subjectList[4].field,
                  subject: Subject.subjectList[4].subject[0],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容",
                  floorImage: "791",shadow: .electricFieldColor),
        EventData(floor: "9F 791教室",
                  field: Subject.subjectList[4].field,
                  subject: Subject.subjectList[4].subject[0],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容",
                  floorImage: "791",shadow: .electricFieldColor),
        EventData(floor: "9F 791教室",
                  field: Subject.subjectList[4].field,
                  subject: Subject.subjectList[4].subject[0],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容",
                  floorImage: "791",shadow: .electricFieldColor),
        EventData(floor: "3F 731教室",
                  field: Subject.subjectList[5].field,
                  subject: Subject.subjectList[5].subject[1],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容",
                  floorImage: "731",shadow: .gameFieldColor),
        EventData(floor: "3F 731教室",
                  field: Subject.subjectList[5].field,
                  subject: Subject.subjectList[5].subject[1],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容",
                  floorImage: "731",shadow: .gameFieldColor),
        EventData(floor: "3F 731教室",
                  field: Subject.subjectList[5].field,
                  subject: Subject.subjectList[5].subject[1],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容",
                  floorImage: "731",shadow: .gameFieldColor),
        EventData(floor: "6F 761教室",
                  field: Subject.subjectList[7].field,
                  subject: Subject.subjectList[7].subject[1],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容",
                  floorImage: "761",shadow: .dataProcessingFieldColor),
        EventData(floor: "6F 761教室",
                  field: Subject.subjectList[7].field,
                  subject: Subject.subjectList[7].subject[1],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容",
                  floorImage: "761",shadow: .dataProcessingFieldColor),
        EventData(floor: "6F 761教室",
                  field: Subject.subjectList[7].field,
                  subject: Subject.subjectList[7].subject[1],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容",
                  floorImage: "761",shadow: .dataProcessingFieldColor),
        EventData(floor: "B1F 7B11教室",
                  field: Subject.subjectList[3].field,
                  subject: Subject.subjectList[3].subject[0],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容",
                  floorImage: "7B11",shadow: .businessFieldColor),
        EventData(floor: "B1F 7B11教室",
                  field: Subject.subjectList[3].field,
                  subject: Subject.subjectList[3].subject[0],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容",
                  floorImage: "7B11",shadow: .businessFieldColor),
        EventData(floor: "B1F 7B11教室",
                  field: Subject.subjectList[3].field,
                  subject: Subject.subjectList[3].subject[0],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容",
                  floorImage: "7B11",shadow: .businessFieldColor),
        EventData(floor: "B1F 7B12教室",
                  field: Subject.subjectList[10].field,
                  subject: Subject.subjectList[10].subject[0],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容",
                  floorImage: "7B12",shadow: .networkFieldColor),
        EventData(floor: "B1F 7B12教室",
                  field: Subject.subjectList[10].field,
                  subject: Subject.subjectList[10].subject[0],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容",
                  floorImage: "7B12",shadow: .networkFieldColor),
        EventData(floor: "B1F 7B12教室",
                  field: Subject.subjectList[10].field,
                  subject: Subject.subjectList[10].subject[0],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容",
                  floorImage: "7B12",shadow: .networkFieldColor),
        EventData(floor: "4F 742教室",
                  field: Subject.subjectList[1].field,
                  subject: Subject.subjectList[1].subject[0],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容",
                  floorImage: "742",shadow: .cgFieldColor),
        EventData(floor: "4F 742教室",
                  field: Subject.subjectList[1].field,
                  subject: Subject.subjectList[1].subject[0],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容",
                  floorImage: "742",shadow: .cgFieldColor),
        EventData(floor: "4F 742教室",
                  field: Subject.subjectList[1].field,
                  subject: Subject.subjectList[1].subject[0],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容",
                  floorImage: "742",shadow: .cgFieldColor),
        EventData(floor: "B2F 7B22教室",
                  field: Subject.subjectList[6].field,
                  subject: Subject.subjectList[6].subject[0],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容",
                  floorImage: "7B22",shadow: .aiFieldColor),
        EventData(floor: "B2F 7B22教室",
                  field: Subject.subjectList[6].field,
                  subject: Subject.subjectList[6].subject[0],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容",
                  floorImage: "7B22",shadow: .aiFieldColor),
        EventData(floor: "B2F 7B22教室",
                  field: Subject.subjectList[6].field,
                  subject: Subject.subjectList[6].subject[0],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容",
                  floorImage: "7B22",shadow: .aiFieldColor),
        EventData(floor: "7F 772教室",
                  field: Subject.subjectList[9].field,
                  subject: Subject.subjectList[9].subject[0],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容",
                  floorImage: "772",shadow: .webFieldColor),
        EventData(floor: "7F 772教室",
                  field: Subject.subjectList[9].field,
                  subject: Subject.subjectList[9].subject[0],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容",
                  floorImage: "772",shadow: .webFieldColor),
        EventData(floor: "7F 772教室",
                  field: Subject.subjectList[9].field,
                  subject: Subject.subjectList[9].subject[0],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容",
                  floorImage: "772",shadow: .webFieldColor),
        EventData(floor: "7F 771教室",
                  field: Subject.subjectList[9].field,
                  subject: Subject.subjectList[9].subject[0],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容",
                  floorImage: "771",shadow: .webFieldColor),
        EventData(floor: "7F 771教室",
                  field: Subject.subjectList[9].field,
                  subject: Subject.subjectList[9].subject[0],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容",
                  floorImage: "771",shadow: .webFieldColor),
        EventData(floor: "7F 771教室",
                  field: Subject.subjectList[9].field,
                  subject: Subject.subjectList[9].subject[0],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容",
                  floorImage: "771",shadow: .webFieldColor),
        EventData(floor: "7F 773教室",
                  field: Subject.subjectList[9].field,
                  subject: Subject.subjectList[9].subject[0],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容",
                  floorImage: "773",shadow: .webFieldColor),
        EventData(floor: "7F 773教室",
                  field: Subject.subjectList[9].field,
                  subject: Subject.subjectList[9].subject[0],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容",
                  floorImage: "773",shadow: .webFieldColor),
        EventData(floor: "7F 773教室",
                  field: Subject.subjectList[9].field,
                  subject: Subject.subjectList[9].subject[0],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容",
                  floorImage: "773",shadow: .webFieldColor),
        EventData(floor: "4F 743教室",
                  field: Subject.subjectList[1].field,
                  subject: Subject.subjectList[1].subject[1],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容",
                  floorImage: "743",shadow: .cgFieldColor),
        EventData(floor: "4F 743教室",
                  field: Subject.subjectList[1].field,
                  subject: Subject.subjectList[1].subject[1],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容",
                  floorImage: "743",shadow: .cgFieldColor),
        EventData(floor: "4F 743教室",
                  field: Subject.subjectList[1].field,
                  subject: Subject.subjectList[1].subject[1],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容",
                  floorImage: "743",shadow: .cgFieldColor),
        EventData(floor: "5F 751教室",
                  field: Subject.subjectList[8].field,
                  subject: Subject.subjectList[8].subject[1],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容",
                  floorImage: "751",shadow: .animationFieldColor),
        EventData(floor: "5F 751教室",
                  field: Subject.subjectList[8].field,
                  subject: Subject.subjectList[8].subject[1],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容",
                  floorImage: "751",shadow: .animationFieldColor),
        EventData(floor: "5F 751教室",
                  field: Subject.subjectList[8].field,
                  subject: Subject.subjectList[8].subject[1],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容",
                  floorImage: "751",shadow: .animationFieldColor),
        EventData(floor: "5F 753教室",
                  field: Subject.subjectList[8].field,
                  subject: Subject.subjectList[8].subject[1],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容",
                  floorImage: "753",shadow: .animationFieldColor),
        EventData(floor: "5F 753教室",
                  field: Subject.subjectList[8].field,
                  subject: Subject.subjectList[8].subject[1],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容",
                  floorImage: "753",shadow: .animationFieldColor),
        EventData(floor: "5F 753教室",
                  field: Subject.subjectList[8].field,
                  subject: Subject.subjectList[8].subject[1],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容",
                  floorImage: "753",shadow: .animationFieldColor),
        EventData(floor: "9F 792教室",
                  field: Subject.subjectList[4].field,
                  subject: Subject.subjectList[4].subject[3],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容",
                  floorImage: "792",shadow: .electricFieldColor),
        EventData(floor: "9F 792教室",
                  field: Subject.subjectList[4].field,
                  subject: Subject.subjectList[4].subject[3],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容",
                  floorImage: "792",shadow: .electricFieldColor),
        EventData(floor: "9F 792教室",
                  field: Subject.subjectList[4].field,
                  subject: Subject.subjectList[4].subject[3],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容",
                  floorImage: "792",shadow: .electricFieldColor),
        EventData(floor: "6F 763教室",
                  field: Subject.subjectList[7].field,
                  subject: Subject.subjectList[7].subject[2],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容",
                  floorImage: "763",shadow: .dataProcessingFieldColor),
        EventData(floor: "6F 763教室",
                  field: Subject.subjectList[7].field,
                  subject: Subject.subjectList[7].subject[2],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容っ",
                  floorImage: "763",shadow: .dataProcessingFieldColor),
        EventData(floor: "6F 763教室",
                  field: Subject.subjectList[7].field,
                  subject: Subject.subjectList[7].subject[2],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容っっっj",
                  floorImage: "763",shadow: .dataProcessingFieldColor),
        EventData(floor: "B1F 7B14教室",
                  field: Subject.subjectList[2].field,
                  subject: Subject.subjectList[2].subject[0],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容っっっっっっっっっっっっっっっっ",
                  floorImage: "7B14",shadow: .designFieldColor),
        EventData(floor: "B1F 7B14教室",
                  field: Subject.subjectList[2].field,
                  subject: Subject.subjectList[2].subject[0],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容っっっっっっっっっっっっっっっ",
                  floorImage: "7B14",shadow: .designFieldColor),
        EventData(floor: "B1F 7B14教室",
                  field: Subject.subjectList[2].field,
                  subject: Subject.subjectList[2].subject[0],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容っっっっっっっっっっっっ",
                  floorImage: "7B14",shadow: .designFieldColor),
        EventData(floor: "4 741教室",
                  field: Subject.subjectList[1].field,
                  subject: Subject.subjectList[1].subject[2],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容っっっっっっっっっっっっ",
                  floorImage: "741",shadow: .cgFieldColor),
        EventData(floor: "4F 741教室",
                  field: Subject.subjectList[1].field,
                  subject: Subject.subjectList[1].subject[2],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容っっっっっっっっっっっっっ",
                  floorImage: "741",shadow: .cgFieldColor),
        EventData(floor: "4F 741教室",
                  field: Subject.subjectList[1].field,
                  subject: Subject.subjectList[1].subject[2],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容っっっっっっっっっっっっっっっ",
                  floorImage: "741",shadow: .cgFieldColor),
        EventData(floor: "3F 733教室",
                  field: Subject.subjectList[5].field,
                  subject: Subject.subjectList[5].subject[2],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容",
                  floorImage: "733",shadow: .gameFieldColor),
        EventData(floor: "3F 733教室",
                  field: Subject.subjectList[5].field,
                  subject: Subject.subjectList[5].subject[2],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容っっっっっっっっっっ",
                  floorImage: "733",shadow: .gameFieldColor),
        EventData(floor: "3F 733教室",
                  field: Subject.subjectList[5].field,
                  subject: Subject.subjectList[5].subject[2],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容っっっ",
                  floorImage: "733",shadow: .gameFieldColor),
        EventData(floor: "9F 791教室",
                  field: Subject.subjectList[4].field,
                  subject: Subject.subjectList[4].subject[2],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容",
                  floorImage: "791",shadow: .electricFieldColor),
        EventData(floor: "9F 791教室",
                  field: Subject.subjectList[4].field,
                  subject: Subject.subjectList[4].subject[2],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容",
                  floorImage: "791",shadow: .electricFieldColor),
        EventData(floor: "9F 791教室",
                  field: Subject.subjectList[4].field,
                  subject: Subject.subjectList[4].subject[2],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容っ",
                  floorImage: "791",shadow: .electricFieldColor),
        EventData(floor: "5F 752教室",
                  field: Subject.subjectList[8].field,
                  subject: Subject.subjectList[8].subject[0],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容っ",
                  floorImage: "752",shadow: .animationFieldColor),
        EventData(floor: "5F 752教室",
                  field: Subject.subjectList[8].field,
                  subject: Subject.subjectList[8].subject[0],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容っっっっっっっっっっっっっっっっ",
                  floorImage: "752",shadow: .animationFieldColor),
        EventData(floor: "5F 752教室",
                  field: Subject.subjectList[8].field,
                  subject: Subject.subjectList[8].subject[0],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容っっっっっっっっっっっっっ",
                  floorImage: "752",shadow: .animationFieldColor),
        EventData(floor: "B2F 7B21教室",
                  field: Subject.subjectList[6].field,
                  subject: Subject.subjectList[6].subject[0],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容っっっっっっっっっっっっ",
                  floorImage: "7B21",shadow: .aiFieldColor),
        EventData(floor: "B2F 7B21教室",
                  field: Subject.subjectList[6].field,
                  subject: Subject.subjectList[6].subject[0],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容っっっっっっっっっっっ",
                  floorImage: "7B21",shadow: .aiFieldColor),
        EventData(floor: "B2F 7B21教室",
                  field: Subject.subjectList[6].field,
                  subject: Subject.subjectList[6].subject[0],
                  startTime: "09 / 21 AM : 10 : 30 ~ 12 : 30",
                  detail: "イベント内容イベント内容",
                  floorImage: "7B21",shadow: .aiFieldColor),
        
    ]
}
